services:
  urls_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
    - "5432:5432"
    volumes:
      - "./scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql"
      - "C:/dev_tmp/postgres:/var/lib/postgresql/data"
